# based on: 
# https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_UP_DEFAULT: nightly-2023-05-01
  CARGO_TERM_COLOR: always
  # note you will find ~/.cargo/bin/ for caching but that we resolve using preperation
  CARGO_CACHE_PATH:  |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/   
  RUSTUP_CACHE_PATH:  |
    ~/.rustup
    ~/.cargo/bin/   
  COMPONENT: clippy,rustfmt,llvm-tools-preview # NOTE: if you change COMPONENT, also increase the CACHE_VERSION!
  CACHE_VERSION: 15


jobs:
  preperation:
    runs-on: ubuntu-latest
    steps:
      - id: cache-rustup
        name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ${{ env.RUSTUP_CACHE_PATH }}
          key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        run: |
            rustup toolchain install ${{ env.RUST_UP_DEFAULT }} --profile minimal --component ${{ env.COMPONENT }}
            rustup default ${{ env.RUST_UP_DEFAULT }}  
          
  build:
    runs-on: ubuntu-latest
    needs: preperation
    steps:
    - id: cache-rustup
      name: Obtain Rust toolchain
      uses: actions/cache/restore@v3
      with:
          path: ${{ env.RUSTUP_CACHE_PATH }}
          key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
          fail-on-cache-miss: true # does not brake the build ?
    - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
      run: echo 'Failed to retrieve cache';exit 1
    - uses: actions/checkout@v4 
    - id: cache-cargo
      name: Restore cargo cache if exists
      uses: actions/cache/restore@v3
      with:
        path: ${{ env.CARGO_CACHE_PATH }}
        key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
    - name: cargo check -> to speedup clippy 
      run: cargo check
    - name: cargo build
      run: cargo build
    - name: Build related test but no execution
      run: cargo test --no-run
    - name: Make '~/.cargo/git/db' in case git repositories are not used
      run:  mkdir -p ~/.cargo/git/db  
    - run: ls ~/.cargo/registry/index/
    - run: ls ~/.cargo/registry/cache/
    - run: ls ~/.cargo/git/db/
    - run: ls target/   
    - name: Save to cargo cache
      uses: actions/cache/save@v3
      with:
        path: ${{ env.CARGO_CACHE_PATH }}
        key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
    # If the tests fail, then at least we have a cache...
    - name: Run tests
      run: cargo test run
            
  fmt:
    needs: [preperation, coverage]
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - id: cache-rustup
        name: Obtain Rust toolchain
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.RUSTUP_CACHE_PATH }}
          key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        run: echo 'Failed to retrieve cache';exit 1
      # The actual job
      - uses: actions/checkout@v4 
      - name: Fmt
        run: cargo fmt --all -- --check

  clippy:
    needs: [build, coverage]
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - id: cache-rustup
        name: Obtain Rust toolchain
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.RUSTUP_CACHE_PATH }}
          key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        run: echo 'Failed to retrieve cache';exit 1
      - id: cache-cargo
        name: Set up cargo cache
        uses: actions/cache/restore@v3
        continue-on-error: false
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: echo 'Failed to retrieve cargo cache';exit 1  
      # The actual job
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy -- -D warnings

        
  coverage:
    needs: build
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - id: cache-rustup
        name: Obtain Rust toolchain
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.RUSTUP_CACHE_PATH }}
          key: toolchain-${{ env.RUST_UP_DEFAULT }}-v${{ env.CACHE_VERSION }}-
      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
        run: echo 'Failed to retrieve cache';exit 1
      - id: cache-cargo
        name: Set up cargo cache
        uses: actions/cache/restore@v3
        continue-on-error: false
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: echo 'Failed to retrieve cargo cache';exit 1  
      - name: Install cargo-llvm-cov
        run: curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
      # The actual job
      - uses: actions/checkout@v4
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true    


