# based on: 
# https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always



jobs:
    lint:
      name: Lint
      runs-on: ubuntu-latest
      env:
        RUSTFLAGS: -D warnings
        CARGO_TERM_COLOR: always
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
        - name: Lint (clippy)
          uses: actions-rs/cargo@v1
          with:
            command: clippy
            args: --all-features --all-targets
#        - name: Lint (rustfmt)
#          uses: actions-rs/cargo@v1
#          with:
#            command: xfmt
#            args: --check
#        - name: Install cargo readme
#          uses: baptiste0928/cargo-install@v1
#          with:
#            crate: cargo-readme
#            version: latest
#        - name: Run cargo readme
#          run: ./scripts/regenerate-readmes.sh
#        - name: Check for differences
#          run: git diff --exit-code
      